version: '2'
services:
#    gift-server:
#      image: everymountain/gift-server
#      ports:
#        - 8080:8080
#        - 11411:11411
#      volume: server/src/main/resources/public:/tmp
    everymountain:
      build:
        context: node
        dockerfile: Dockerfile
      ports:
        - "80:3000"
      volumes:
        - ./node/endpoints:/app/endpoints
        - ./node/public:/app/public
