version: '2'
services:
#    gift-server:
#      image: everymountain/gift-server
#      ports:
#        - 8080:8080
#        - 11411:11411
#      volume: server/src/main/resources/public:/tmp
    gift-server:
      build:
        context: node
        dockerfile: Dockerfile
      ports:
        - "80:3000"
      volumes:
        - ./node/endpoints:/app/endpoints
        - ./node/public:/app/public
    gift-db:
      image: elasticsearch
      ports:
        - "9200:9200"
        - "9300:9300"

